### ISSUE TITLE
dataset.py seems to be missing

### ISSUE THREAD

**Issue by vadimkantorov** [evelinehong/slot-attention-pytorch#1]
Thanks for your code!

The dataset.py seems to be missing. In the meanwhile I'll try to adapt https://github.com/vahidk/tfrecord/ to read directly DeepMind's https://github.com/deepmind/multi_object_datasets#clevr-with-masks

**Comment by evelinehong** [comment]
Hi Vadim,
I believe dataset.py is easy to write and it depends on your data path.
You only have to return {'image': image} like this:
    def __getitem__(self, index):
        path = self.files[index]
        image = Image.open(path).convert("RGB")
        image = image.resize((128 , 128))
        image = self.img_transform(image)
        sample = {'image': image}

        return sample
            
    
    def __len__(self):
        return len(self.files)

And you can define your own transformations of the image.
Best,
Yining

**Comment by vadimkantorov** [comment]
Thanks!

**Comment by vadimkantorov** [comment]
(just FYI I placed my reimpl at https://github.com/vadimkantorov/yet_another_pytorch_slot_attention, an interesting part is that I converted the original checkpoint (but haven't adapted code to load it yet))
